#!/bin/bash
echo "Pushing tag $DOCKER_REPO:$SOURCE_COMMIT"
docker push $DOCKER_REPO:$SOURCE_COMMIT

echo "Tagging image $DOCKER_REPO:$SOURCE_COMMIT with tag $DOCKER_REPO:latest"
docker tag $DOCKER_REPO:$SOURCE_COMMIT $DOCKER_REPO:latest

echo "Pushing tag $DOCKER_REPO:latest"
docker push $DOCKER_REPO:latest
